# Generated by Django 2.1.7 on 2020-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='IDNumber',
            field=models.IntegerField(null=True),
        ),
    ]
