# Generated by Django 2.1.7 on 2020-04-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_report_idnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='CrimeDesciption',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='SureName',
        ),
    ]
